# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Feelgoodbot < Formula
  desc "Malware detection for macOS - know when you've been compromised"
  homepage "https://feelgoodbot.com"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kris-hansen/feelgoodbot/releases/download/v0.1.3/feelgoodbot_0.1.3_darwin_amd64.tar.gz"
      sha256 "abd1e6c03d71268775943618af72522580923f429ed2bb079e7fbe96bf547141"

      define_method(:install) do
        bin.install "feelgoodbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kris-hansen/feelgoodbot/releases/download/v0.1.3/feelgoodbot_0.1.3_darwin_arm64.tar.gz"
      sha256 "a6fb2478090f4b0ef5a3a8e1786ab34434ce9ccd5d5ff9546201e551e46e7313"

      define_method(:install) do
        bin.install "feelgoodbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/feelgoodbot/releases/download/v0.1.3/feelgoodbot_0.1.3_linux_amd64.tar.gz"
      sha256 "75468f90a49434f64b521099163cb41f259f78d01d4259838b02972aab577fba"
      define_method(:install) do
        bin.install "feelgoodbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/feelgoodbot/releases/download/v0.1.3/feelgoodbot_0.1.3_linux_arm64.tar.gz"
      sha256 "90421db848516401fd7b0c95ddfdcf27dfcc58bc3e2fb16603190387896d868e"
      define_method(:install) do
        bin.install "feelgoodbot"
      end
    end
  end

  test do
    system "#{bin}/feelgoodbot", "version"
  end
end
