# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Feelgoodbot < Formula
  desc "Malware detection for macOS - know when you've been compromised"
  homepage "https://feelgoodbot.com"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kris-hansen/feelgoodbot/releases/download/v0.1.7/feelgoodbot_0.1.7_darwin_amd64.tar.gz"
      sha256 "2cf66a45e5dbd75dfe2d76a345a005c4ae9f93043883c0954b4be6f20496fdfe"

      define_method(:install) do
        bin.install "feelgoodbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kris-hansen/feelgoodbot/releases/download/v0.1.7/feelgoodbot_0.1.7_darwin_arm64.tar.gz"
      sha256 "25e464310f26faf75504866b3b9c762dd7460c44b23706fc293a36fad8681f67"

      define_method(:install) do
        bin.install "feelgoodbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/feelgoodbot/releases/download/v0.1.7/feelgoodbot_0.1.7_linux_amd64.tar.gz"
      sha256 "82ee69111bc4db9fc9564b7e0935444d3984a55dfdbe49d9df70ad9dc95e3409"
      define_method(:install) do
        bin.install "feelgoodbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/feelgoodbot/releases/download/v0.1.7/feelgoodbot_0.1.7_linux_arm64.tar.gz"
      sha256 "44f68d4927762cd043e0840266e80f03c7f1a71ddfc3330e4bd1ab7fe88b581e"
      define_method(:install) do
        bin.install "feelgoodbot"
      end
    end
  end

  test do
    system "#{bin}/feelgoodbot", "version"
  end
end
